### ISSUE TITLE
Moodle Plugin Publishing

### ISSUE THREAD

**Issue by nobicycle** [SergioComeron/moodle-mod-jitsi#1]
Hello Sergio

Thank you for publishing this plugin.

It looks like you also preferred  Jitsi iversus Openmeetings and  BigBlueButton.

I wondered why you did not publish your plugin on https://moodle.org/plugins/
?
If this was done, perhaps collaborators on your plugin would join. (Sorry I'm no help with JS)

If you don't have time to do so, I would do it for you putting you as the author and your github account as reference.

best wishes

**Comment by SergioComeron** [comment]
Hello!
thanks for the comment. Yes, it is a project that started and the idea is to publish the plugin in the moodle repository. However, although now it is minimally functional, I still need to make some changes. I hope to have time these days and upload it.
I will keep you informed.

Thank you!

**Comment by nobicycle** [comment]
Great stuff!

**Comment by SergioComeron** [comment]
Hi nobicycle, 
I inform you that I already have the plugin in review for Moodle and may soon be in the repository.

**Comment by nobicycle** [comment]
Thank you very much.
I see there may be some translation required in lang/en/jitsi.php
I will send a pull to include Indonesian when ready.
best wishes

**Comment by SergioComeron** [comment]
Hi!
I have good news, the plugin has been approved and you have it available for download. (https://moodle.org/plugins/mod_jitsi)
It is not yet available in AMOS for translation (usually take a few days) but in a few days it will be possible to translate.

I hope you find it helpful. :)
